name: Fix build conflict - Run build commands
on:
  pull_request:
    types: [ labeled ]

jobs:
    build-run:
        if: ${{ github.event.label.name == 'conflict' }}
        runs-on: ubuntu-latest
        name: 'Run npm build commands'
        steps:
            - name: 'Checkout'
              uses: actions/checkout@master

            - name: Use desired version of NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 14.17

            - name: Cache node modules
              id: cache-node
              uses: actions/cache@v2
              env:
                cache-name: cache-node-modules
              with:
                path: ~/.npm
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

            - name: Initialize mandatory git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "noreply@github.com"

            - name: Extract current branch name
              id: extract_branch
              run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

            - name: Install dependencies and build
              run: npm install

            - name: Run build
              run: npm run build

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v3
              with:
                  commit-message: Auto build generated
                  base: ${{ steps.extract_branch.outputs.branch }}
                  branch: ${{ steps.extract_branch.outputs.branch }}-build
                  delete-branch: true
                  title: 'Updated the build files'
                  body: |
                      Update report
                      Hi!
                        This PR was created in response workflow running.
                        I've updated the build files.

            - name: Check outputs
              run: |
                  echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
                  echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

            - uses: andymckay/labeler@1.0.4
              with:
                remove-labels: "conflict"
